language: generic
sudo: false # use container based build

env:
  - PYTHON_VERSION=3.6

os:
  - linux
  - osx

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        export "DISPLAY=:99.0";
        sh -e /etc/init.d/xvfb start;
        sleep 3;
    fi

install:
  - |
      echo ""
      echo "Configuring conda."
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install conda-build
      conda info -a
script:
- conda build conda-recipe
