image:
    - Visual Studio 2015
    - Ubuntu


environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.6
        - PYTHON: "C:\\Miniconda37-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.7

install:
    # windows config (for installation)
    - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    # linux installation
    - sh: |
          sudo apt-get update
          sudo apt-get install alsa-lib libXScrnSaver libXcomposite libXcursor libXi libXrandr libXtst mesa-libEGL mesa-libGL
    - sh: |
          MINICONDA_URL="https://repo.continuum.io/miniconda"
          MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
          curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
          bash $MINICONDA_FILE -bp $HOME/miniconda3
          source $HOME/miniconda3/bin/activate root
          hash -r
    # conda config
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda config --add channels chilipp
    - conda config --add channels chilipp/label/master
    - conda config --add channels chilipp/label/dev
    - conda update -q conda
    - conda install conda-build anaconda-client
    - conda info -a
    - conda list
    # windows config
    - cmd: 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - cmd: "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET GIT_BRANCH=%APPVEYOR_REPO_BRANCH%)"
    # linux config
    - sh: 'echo "backend : module://psyplot_gui.backend" > matplotlibrc'
    - sh: 'export MATPLOTLIBRC=`pwd`/matplotlibrc'
    - sh: export PYTHONWARNINGS='ignore:mode:DeprecationWarning:docutils.io:245'
    - sh: if [[ $APPVEYOR_REPO_TAG_NAME == "" ]]; then export GIT_BRANCH=$APPVEYOR_REPO_BRANCH; fi

build: off

test_script:
    - cmd: conda build conda-recipe --python %PYTHON_VERSION%
    - sh: conda build conda-recipe --python $PYTHON_VERSION

deploy_script:
    - cmd: "python ci\\deploy_anaconda.py"
    - sh: "python ci/deploy_anaconda.py"
