environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.6
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.7

install:
    - "SET ORIGPATH=%PATH%"
    - setlocal
    - set CONDA_REPO_TOKEN=
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda config --add channels chilipp/label/dev
    - conda config --add channels chilipp/label/master
    - conda config --add channels chilipp
    - conda update -q conda
    - conda install conda-build anaconda-client
    - conda info -a
    - conda list
    - 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - endlocal

build: off

test_script:
    - setlocal
    - set CONDA_REPO_TOKEN=
    - conda build conda-recipe --python %PYTHON_VERSION%
    - endlocal

deploy_script:
    - cmd: "python ci\\deploy_anaconda.py"
