environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.7
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.6

install:
    # windows config (for installation)
    - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - cmd: setlocal
    - cmd: set CONDA_REPO_TOKEN=
    # conda config
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda config --add channels chilipp
    - conda config --add channels chilipp/label/master
    - conda config --add channels chilipp/label/dev
    - conda update -q conda
    - conda install conda-build anaconda-client
    - conda info -a
    - conda list
    # windows config
    - cmd: endlocal
    - cmd: 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - cmd: "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET GIT_BRANCH=%APPVEYOR_REPO_BRANCH%)"

build: off

test_script:
    - cmd: setlocal
    - cmd: set CONDA_REPO_TOKEN=
    - cmd: conda build conda-recipe --python %PYTHON_VERSION%
    - cmd: endlocal

deploy_script:
    - cmd: "python ci\\deploy_anaconda.py"
