environment:
    STRADITIZE_PYTHON: "C:\\straditize-conda-installation"

    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
        - PYTHON: "C:\\Miniconda36"
          PYTHON_ARCH: "32"

install:
    - "SET ORIGPATH=%PATH%"
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda install conda-build constructor
    - conda info -a

build: false

test_script:
    - conda build conda-recipe
    - constructor straditize-conda
    # test installer
    - "powershell ./ci/install_straditize_conda.ps1"
    - "SET PATH=%STRADITIZE_PYTHON%;%STRADITIZE_PYTHON%\\Scripts;%ORIGPATH%"
    - pip install pytest
    - py.test -xv tests/widgets/test_samples_table.py
