{% set data = load_setup_py_data() %}

package:
  name: straditize
  version: {{ data.get('version') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ CONDA_PY }}_{{ environ.get('GIT_BUILD_STR', '') }}{% if environ.get('GIT_BRANCH') %}_{{ environ.get('GIT_BRANCH').replace('-', '') }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 27]
  entry_points:
    - straditize = straditize.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psyplot-gui >=1.2.3
    - psyplot >=1.2.0
    - netcdf4
    - pyqt >=5
    - scipy
    - numpy >=1.12  # [win]
    - scikit-image
    - openpyxl
    - sphinx !=1.7.5
    - psy-strat

test:
  requires:
    - pytest
    - codecov
    - pytest-cov >=2.6.1
    - tesserocr  # [not win]
    - psutil
  source_files:
    - tests
  imports:
    - straditize
    - straditize.widgets
  commands:
    - straditize --help
    - pytest -v --cov=straditize
      --ignore=tests/widgets/test_selection_toolbar.py
      --ignore=tests/widgets/test_samples_table.py
      --ignore=tests/widgets/test_beginner.py
      --ignore=tests/widgets/test_hoya_del_castillo.py
    - pytest -v --cov=straditize --cov-append tests/widgets/test_selection_toolbar.py::StraditizerSelectionToolsTest
    - pytest -v --cov=straditize --cov-append tests/widgets/test_selection_toolbar.py::ReaderSelectionToolsTest
    - pytest -v --cov=straditize --cov-append tests/widgets/test_selection_toolbar.py::ReaderGreyScaleToolsTest
    - pytest -v --cov=straditize --cov-append tests/widgets/test_samples_table.py
    - pytest -v --cov=straditize --cov-append tests/widgets/test_beginner.py
    - pytest -v --cov=straditize --cov-append tests/widgets/test_hoya_del_castillo.py
    - codecov

app:
  entry: straditize
  icon: logo.png
  summary: Stratigraphic Diagram Digitization software
  type: desk

about:
  home: https://github.com/Chilipp/straditize
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Python package for digitizing pollen diagrams'

  description: |
    A software for a semi-automatic digitization of pollen diagrams or
    other types of stratigraphic diagrams using the command line or a
    graphical user interface.
  doc_url: http://straditize.readthedocs.io/
  dev_url: https://github.com/Chilipp/straditize

extra:
  recipe-maintainers:
    - Chilipp
