{% set name = "straditize" %}
{% set version = "0.0.1.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - straditize = straditize.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - psyplot-gui >=1.2.2
    - psyplot >=1.2.0
    - netcdf4
    - pyqt >=5.7.0
    - scipy
    - scikit-image
    - openpyxl
    - sphinx !=1.7.5
    - psy-strat

test:
  requires:
    - pytest
    - codecov
    - pytest-cov>=2.6.1
    - tesserocr  # [not win]
  source_files:
    - tests
  imports:
    - straditize
    - straditize.widgets
  commands:
    - straditize --help
    - pytest -sv --cov=straditize
      --ignore=tests/widgets/test_selection_toolbar.py
      --ignore=tests/widgets/test_samples_table.py
    - pytest -sv --cov=straditize --cov-append
      tests/widgets/test_selection_toolbar.py
      tests/widgets/test_samples_table.py
    - codecov


about:
  home: https://github.com/Chilipp/straditize
  license: GPLv2
  license_family: GPL2
  license_file: LICENSE
  summary: 'Python package for digitizing pollen diagrams'

  description: |
    This program tackles this problem by providing a python package to digitize
    especially pollen diagrams, but also any other type of stratigraphic diagram.
  doc_url: http://straditize.readthedocs.io/
  dev_url: https://github.com/Chilipp/straditize

extra:
  recipe-maintainers:
    - Chilipp
