{% set name = "straditize" %}
{% set version = "0.0.1.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - straditize=straditize.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - psyplot-gui
    - pyqt>=5.6.0
    - scipy
    - scikit-image
    - openpyxl
    - sphinx!=1.7.5

test:
  requires:
    - pytest
    - codecov
    - pytest-cov
  source_files:
    - tests
  imports:
    - straditize
    - straditize.widgets
  commands:
    - straditize --help
    - pytest -v --cov=straditize -v
      --ignore=tests/widgets/test_selection_toolbar.py
      --ignore=tests/widgets/test_samples_table.py
    - pytest -v --cov=straditize -v --cov-append
      tests/widgets/test_selection_toolbar.py
      tests/widgets/test_samples_table.py
    - codecov


about:
  home: https://github.com/Chilipp/straditize
  license: GPLv2
  license_family: GPL2
  license_file: LICENSE
  summary: 'Python package for digitizing pollen diagrams'

  description: |
    This program tackles this problem by providing a python package to digitize
    especially pollen diagrams, but also any other type of stratigraphic diagram.
  doc_url: http://straditize.readthedocs.io/
  dev_url: https://github.com/Chilipp/straditize

extra:
  recipe-maintainers:
    - Chilipp
